---
- name: add apt_repository
  apt_repository: repo='ppa:vbernat/haproxy-1.5' state=present update_cache=yes


- name: install haproxy and socat
  apt: pkg={{ item }} state=latest
  with_items:
  - haproxy
  - socat

- name: copy certificate files
  copy: src=roles/lb/files/ dest=/etc/haproxy/ 

- name: enable haproxy
  lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  notify: restart haproxy 

- name: deploy haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
